### ISSUE TITLE
Move API documentation to doxygen.librepcb.org?

### ISSUE THREAD

**Issue by ubruhin** [LibrePCB/librepcb-doc#22]
https://docs.librepcb.org is intended for *user* documentation. But is [API documentation](https://docs.librepcb.org/#api) for users? Basically a user could also be interested in writing a script or so which fetches the list of available libraries from our server. But probably most users don't access the API directly, so I  wonder if we should move the API documentation to our developers documentation at https://doxygen.librepcb.org to keep users documentation clean.

Actually I already gave it a try :wink:, see https://doxygen.librepcb.org/_branches/add-api-documentation/d1/dcb/doc_server_api.html

Any thoughts?

EDIT: Actually the API specification is somehow similar to the file format specification, which is also documented at https://doxygen.librepcb.org...

**Comment by dbrgn** [comment]
Yeah makes sense :)

By the way, I think it would be good to rename the subdomain from "doxygen" to something like "dev" or "developers". It's much more than just class documentation, and I keep forgetting that :slightly_smiling_face:

**Comment by ubruhin** [comment]
> By the way, I think it would be good to rename the subdomain from "doxygen" to something like "dev" or "developers"

Hmm yeah I can do that (the old domain could then be redirected to the new one to avoid dead links).

**Comment by dbrgn** [comment]
> old domain could then be redirected to the new one to avoid dead links

HTTP 301 Moved Permanently :slightly_smiling_face:

**Comment by ubruhin** [comment]
> HTTP 301 Moved Permanently

Yep :smiley: 

- API documentation now available at https://developers.librepcb.org/d1/dcb/doc_server_api.html
- API documentation removed from docs.librepcb.org
- https://doxygen.librepcb.org now redirects to https://developers.librepcb.org
