### ISSUE TITLE
Conventions: Label alignment

### ISSUE THREAD

**Issue by dbrgn** [LibrePCB/librepcb-doc#24]
I would add the following requirements:

- Generally, all symbols should have the `{{ NAME }}` label at the top and the `{{ VALUE }}` label at the bottom
- Generally, all packages should have the `{{ NAME }}` label at the top and the `{{ VALUE }}` label at the bottom
- For IC-like symbols, the labels should be aligned on the top and bottom line of the rectangle.

The question that already arose multiple times in practice was the question of left/right/center alignment. I feel that centering makes best use of the available screen and/or PCB space. This does not matter for short names, but it will for long names. Some examples:

Small symbol, short text:

![img](https://tmp.dbrgn.ch/screenshots/20181118221526-4bj4kbhj.png)

Small symbol, long text:

![img](https://tmp.dbrgn.ch/screenshots/20181118222001-49p3i1ho.png)

Large symbol, short text:

![img](https://tmp.dbrgn.ch/screenshots/20181118221746-iivbxs51.png)

Large symbol, long text:

![img](https://tmp.dbrgn.ch/screenshots/20181118221811-_xbvx503.png)

Note that usually large symbols are much more "filled" with text, so the designator will look less "lost".

For packages, the labels can be moved around by the user, for symbols that's currently not possible.

Style wise I don't really care, I think that the small symbols look better centered and the larger ones look better left-aligned (maybe starting from a width of 8 * 2.54mm). We could make a rule of that, but it makes things more complicated for the user and costs more time during library contribution review.

However, from screen space usage there might be a clear "better".

Opinions, @ubruhin @rnestler @eduardosm @HBadertscher?

**Comment by rnestler** [comment]
Hmm the [current suggestion](https://docs.librepcb.org/#libraryconventions) is to use left aligned for symbols and centered for packages. Is this still open for discussions or should we close this issue?

**Comment by dbrgn** [comment]
It would be OK for me even though I find the current rule a bit inconsistent. I would prefer the same alignment for both, and don't really care whether alignment is in the center or on the left (although centered alignment makes better use of horizontal screen/pcb space).

**Comment by rnestler** [comment]
@ubruhin As the BDFL of this project we need a decision from you :wink:

**Comment by ubruhin** [comment]
> As the BDFL of this project we need a decision from you

Ok, then let's keep it as-is :grin:
