### ISSUE TITLE
Conventions: Footprint / symbol line width

### ISSUE THREAD

**Issue by dbrgn** [LibrePCB/librepcb-doc#4]
The current line width in the package and symbol editors is 0.25mm. Should we keep that? Is there a certain rationale for that choice?

![screenshot](https://tmp.dbrgn.ch/screenshots/20180404223824-95m7_pgq.png)

![screenshot2](https://tmp.dbrgn.ch/screenshots/20180404223921-iohr4et_.png)

In what cases should a library designer deviate from those values?

**Comment by ubruhin** [comment]
IMHO the line width of symbols looks good so far and there shouldn't be a reason to change that.

But for footprints we should follow IPC-7351 which contains some recommendations about line widths (the width depends on various parameters, so there isn't one width which can be used for everything).

**Comment by ubruhin** [comment]
The library conventions now contain recommended line widths for both footprints and symbols, so I would say this can be closed.
