### ISSUE TITLE
Installation of asciidoctor-pdf on MacOsx

### ISSUE THREAD

**Issue by savoie-supra** [LibrePCB/librepcb-doc#59]
Hello,

I followed the installation instructions on MacOSX :
**"On Mac you can use homebrew and install gems in your user folder:

brew install asciidoctor
gem install --user-install pygments.rb rouge"**

But to build the pdf file with the command "asciidoctor-pdf index.adoc      # build index.pdf" it is also required to install asciidoctor-pdf on MacOSX

I would suggest to add in the installation part for MacOSX of the readme file this missing line: **gem install asciidoctor-pdf** 

Best regards,
Pascal

**Comment by ubruhin** [comment]
Hi! This is now clarified in #65 (although unfortunately not an improvement for macOS users, I'm sorry about that).
