### ISSUE TITLE
Any kind of DXF or picture import?

### ISSUE THREAD

**Issue by jabadabado** [LibrePCB/librepcb-doc#60]
Really Great software! 

I though when checking it...the most important is here! But then I could not find any way if importing a PCB shape with reference holes via a DXF file etc. Maybe some other way? Through a picture, PDF, or anything that has the exact sizes to begin the board outline and mounting holes etc.

Did I miss something?

**Comment by ubruhin** [comment]
Closing this in favor of https://github.com/LibrePCB/LibrePCB/issues/891.
